version: "3.7"

services: 

    service_1:
        image: coolwill92/service_1
        ports: 
            - "5000:5000"
        networks: 
            - william_network
        depends_on: 
            - service_4
            - service_2
            - service_3
        deploy:
            replicas: 2


        #environment:
        #    - SQLHOST=$(MYSQL_HOST)
        #    - PASSWORD=$(MYSQL_PASSWORD)
        #    - PORT=$(MYSQL_PORT)
        #    - USER=$(MYSQL_USER)
        #    - DBNAME=$(MYSQL_DB_NAME)}
            
    service_2:
        image: coolwill92/service_2
        networks: 
            - william_network
        deploy:
            replicas: 2  

    service_3:
        image: coolwill92/service_3
        networks: 
            - william_network
        deploy:
            replicas: 2

    service_4:
        image: coolwill92/service_4
        networks: 
            - william_network
        environment: 
            - SAMPLE=HELLO
        deploy:
            replicas: 2

            
networks:
    william_network:
        driver: overlay
