version: "3.7"

services: 

    service_1:
        image: coolwill92/service_1
        ports: 
            - "5000:5000"
        networks: 
            - william_network
        depends_on: 
            - service_4
            - service_2
            - service_3
        deploy:
            replicas: 2
        environment: 
            - SECRET_KEY=${SECRET_KEY}   
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_HOST=${MYSQL_HOST}
            - MYSQL_PORT=${MYSQL_PORT}
            - MYSQL_DB_NAME=${MYSQL_DB_NAME}
            
    service_2:
        image: coolwill92/service_2
        networks: 
            - william_network
        deploy:
            replicas: 2  

    service_3:
        image: coolwill92/service_3
        networks: 
            - william_network
        deploy:
            replicas: 2

    service_4:
        image: coolwill92/service_4
        networks: 
            - william_network
        deploy:
            replicas: 2

            
networks:
    william_network:
        driver: overlay
